ImdbClone/urls.py
from django.urls import path
from . import views

app_name = 'imdb'

urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<int:type_no>/', views.detail, name='detail'),
    # path('detail', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('register', views.register, name='register'),
    path('login', views.auth_login, name='login'),
    path("logout", views.logout_request, name= "logout"),
    ]

Imdb_clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ImdbClone.urls')),
]

ImdbClone/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Celebrity(User):
    # firstName = models.CharField(max_length=100)
    # lastName = models.CharField(max_length=200)
    ROLE_CHOICES = [
        ('Director', 'D'),
        ('Writer', 'W'),
        ('Star', 'S'),
    ]
    born_date = models.DateField(blank=True)
    city = models.CharField(blank=True, max_length=100)
    role = models.CharField(choices=ROLE_CHOICES, max_length=10)

    class Meta:
        verbose_name = 'Celebrity'


class Movie(models.Model):
    CATEGORY_CHOICES = [
        ('action', 'ACTION'),
        ('drama', 'DRAMA'),
        ('comedy', 'COMEDY'),
        ('romance', 'ROMANCE'),
        ('sci-fi', 'SCI-FI'),
        ('crime', 'CRIME'),
        ('Thriller', 'THRILLER'),
    ]

    STATUS_CHOICES = [
        ('RA', 'Recently Added'),
        ('MW', 'Most Watched'),
        ('TR', 'Top Rated'),
        ('IT', 'In Theatres'),
        ('CS', 'Coming Soon'),
    ]
    title = models.CharField(max_length=100)
    desc = models.TextField(max_length=1000)
    imageURL = models.TextField(max_length=10000)
    videoURL = models.TextField(max_length=10000)
    # image = models.ImageField(upload_to='movies')
    # banner = models.ImageField(upload_to='movies_banner')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)
    year = models.DateField()
    rating = models.DecimalField(max_digits=10, decimal_places=1)
    rating_count = models.IntegerField()
    # cast = models.ManyToManyField(Celebrity)

    def __str__(self):
        return self.title

imdb/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

ImdbClone/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput, EmailInput, PasswordInput

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.


class RegistrationForm(UserCreationForm):
    # email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        widgets = {
            'username': TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;height: 40px;border-radius: 5px;',
                'placeholder': 'Name'
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;height: 40px;border-radius: 5px;',
                'placeholder': 'Email'
            }),
            'password1': PasswordInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;height: 40px;border-radius: 5px;',
                'placeholder': 'Email'
            }),
            'password2': PasswordInput(attrs={
                'class': "form-control",
                'style': 'max-width: 300px;height: 40px;border-radius: 5px;',
                'placeholder': 'Email'
            }),
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

ImdbClone/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegistrationForm
from .models import Movie


def home(request):
    model = Movie
    movieData = Movie.objects.all()[:4]
    topRated = Movie.objects.all().filter(rating__gt=7.9)
    comingList = Movie.objects.all().filter(status='CS')
    inTheatreList = Movie.objects.all().filter(status='IT')
    context = {
        'movieList': movieData,
        'topList': topRated,
        'comingList': comingList,
        'inTheatreList': inTheatreList
    }
    print(topRated)
    return render(request, 'imdb_urls/home.html', context)


def detail(request, type_no):
    modelName = Movie
    print(type_no)
    details = Movie.objects.filter(id=type_no)
    context = {
        'details': details[0]
    }

    return render(request, 'imdb_urls/detail.html', context)


def search(request):
    query = request.GET.get('search')

    if query:
        results = Movie.objects.all().filter(title__icontains=query)
    else:
        results = []
    print(results)
    return render(request, 'imdb_urls/search.html', {'search': query, 'results': results})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registered Successfully')
            return redirect('imdb_urls:home')
            messages.error(request, 'Not able to Register. Invalid information')
    else:
        form = RegistrationForm()
    context = {'form': form}
    return render(request, 'imdb_urls/register.html', context)


def auth_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                messages.info(request, "Successfully logged in")
                return redirect("imdb:home")
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'imdb_urls/login.html', context)


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("imdb:home")

imdb/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
from django.shortcuts import render

# Create your views here.

ImdbClone/templates/imdb_urls/detail.html
{% extends 'imdb_urls/header.html' %}
{% block body_block %}
<body>
<div style="padding: 0 30px">
    <p class="ls__tle">{{ details.title }}</p>
    <p> {{ details.desc }}</p>
    <p> Genre: <span style="text-transform: capitalize"> {{ details.category }}</span>  </p>
    <p>Director: <span>Matt Reeves</span></p>
    <p>Stars: <span>Robert Pattinson, Zoe Kravitz</span></p>
    <p style="display: flex;align-items: center">
                           <span>Rating: </span> <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ details.rating }}</span>
    </p>
    <iframe width="1200px" height="600px" src={{ details.videoURL }} frameborder="0" allowfullscreen/>


</div>
</body>
{% endblock %}

ImdbClone/templates/imdb_urls/header.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'imdb/style.css' %}"/>
    <title> Imdb - {% block title %} Ratings, Reviews and where to watch movies! {% endblock %}</title>
</head>
<body class="cn">
<div class="" >
<div class="hd__cn">
    <a href= "{% url 'imdb:home' %}">   <img class="logo" src="../../static/images/imdb1.webp"  /> </a>
<div class="hd__l">
        <p class="hd__txt"><a href= "{% url 'imdb:search' %}"> <img style="width:20px;padding-right:10px" src="../../static/images/search.png" /> </a> </p>
{% if user.is_authenticated %}
      <p class="hd__txt">Hi {{ user.username}}</p>
      <p class=""><a href= "/logout"> Logout </a> </p>

     {% else %}
    <p class="hd__txt"><a href= "{% url 'imdb:register' %}"> Register </a> </p>
        <p class=""><a href= "{% url 'imdb:login' %}"> SignIn </a> </p>
     {% endif %}
</div>

</div>
    {% block body_block %}*** {% endblock %}
</div>
<div>
    <ul>
{#        <li class="hbar1"><a href="http://127.0.0.1:8000/about/"> Find out about this site </a></li>#}
{#        <li class="hbar1"><a href = "{% url 'imdb:index'%}"> Click here to return to main page </a><br/></li>#}

{#        <li class="hbar1"><a href= "{% url 'imdb:logout' %}"> Logout </a> </li>#}
    </ul>
</div>
</body>

ImdbClone/templates/imdb_urls/home.html
{% extends 'imdb_urls/header.html' %}
{% block body_block %}
<body>

<div>
     <img class="banner"src="../../static/images/banner.jpeg" />
</div>

<div style="padding: 0 30px">
    <p class="ls__tle">Featured Today</p>
    <div style="display: flex;width: 100%;overflow-x: scroll">
    {%  for movie in movieList %}
        <a style="color:white;text-decoration: none;" href="{% url 'imdb:detail' movie.id %}">
         <div class="mv__img">
                  <img src={{ movie.imageURL }} />
            <p> {{ movie.title }}</p>
            <p style="display: flex;align-items: center">
                            <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ movie.rating }}</span>
            </p>
         </div>
        </a>

     {% endfor %}
        </div>
    <p class="ls__tle">Top Rated</p>
   <div style="display: flex;width: 100%;overflow-x: scroll">
    {%  for movie in topList %}
                <a style="color:white;text-decoration: none;" href="{% url 'imdb:detail' movie.id %}">

         <div class="mv__img">
                  <img src={{ movie.imageURL }} />
            <p> {{ movie.title }}</p>
            <p style="display: flex;align-items: center">
                            <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ movie.rating }}</span>
            </p>
                 </div>
                </a>

     {% endfor %}
        </div>

    <p class="ls__tle">In Theatres</p>
   <div style="display: flex;width: 100%;overflow-x: scroll">
    {%  for movie in inTheatreList %}
                <a style="color:white;text-decoration: none;" href="{% url 'imdb:detail' movie.id %}">

         <div class="mv__img">
                  <img src={{ movie.imageURL }} />
            <p> {{ movie.title }}</p>
            <p style="display: flex;align-items: center">
                            <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ movie.rating }}</span>
            </p>
                 </div>
                </a>
     {% endfor %}
        </div>

    <p class="ls__tle">Coming soon</p>
   <div style="display: flex;width: 100%;overflow-x: scroll">
    {%  for movie in comingList %}
                <a style="color:white;text-decoration: none;" href="{% url 'imdb:detail' movie.id %}">

         <div class="mv__img">
                  <img src={{ movie.imageURL }} />
            <p> {{ movie.title }}</p>
            <p style="display: flex;align-items: center">
                            <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ movie.rating }}</span>
            </p>
                 </div>
                </a>
     {% endfor %}
        </div>
        </div>

        </div>

</div>

</body>
{% endblock %}

ImdbClone/templates/imdb_urls/login.html
{% extends 'imdb_urls/header.html' %}
{% block body_block %}
<body>
<h1>Login to know more about exciting movies!</h1>
<form class="rs__cn" method="post">
		{% csrf_token %}

{#        {% if form.errors %}#}
{#             {% for field in form %}#}
{#           {% for error in field.errors %}#}
{#              <div class="alert alert-danger">#}
{#                   <strong>{{ error|escape }}</strong>#}
{#              </div>#}
{#           {% endfor %}#}
{#       {% endfor %}#}
{#            {% else %}#}
{#            <p>Logged in Successfully</p>#}
{#        {% endif %}#}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

        {{ form }}

        <input style="margin-top:30px;background-color: #f5c518;color:black;text-transform: uppercase;font-size:20px" type="submit" value="Login">

    </form>
</body>
</html>
{% endblock %}

ImdbClone/templates/imdb_urls/logout.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome, {{user.username}}</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="/login">Login</a>
      </li>

      {% endif %}
    </ul>
  </div>
</nav>

ImdbClone/templates/imdb_urls/register.html
{% extends 'imdb_urls/header.html' %}
{% block body_block %}
<body>
<h1>Registration to know world's exciting movies!</h1>
    <form class="rs__cn" method="post" action="{% url 'imdb:register' %}">

    {% csrf_token %}
    {{ form }}

        <input style="background-color: #f5c518;color:black;text-transform: uppercase;font-size:20px" type="submit" value="register">
    </form>
</body>
</html>
{% endblock %}

ImdbClone/templates/imdb_urls/search.html
{% extends 'imdb_urls/header.html' %}
{% block body_block %}
<body>
<div style="padding: 0 30px">
<form  action="{% url 'imdb:search' %}">
     <input style="width:74%;padding:10px;max-width:1000px;font-size: 18px" type="text"  name="search" placeholder="Search any movies"/>
    <input style="width: 300px;height:64px;background-color: #f5c518" type="submit" value="Search">
</form>
</div>
{% if search %}
<div style="display: flex;flex-flow: wrap;padding:25px">
        {%  for movie in results %}
        <div class="mv__img">
            <img src={{ movie.imageURL }} />
                        <p> {{ movie.title}}</p>
<p style="display: flex;align-items: center">
                            <img style="width:30px;"src="../../static/images/rat.png" />
                            <span style="padding: 10px">{{ movie.title }}</span>
            </p>
        </div>
             {% empty %}

   <h3>No results found.</h3>
       {% endfor %}
  {% endif %}
</div>
</body>
{% endblock %}